identifier: m97a26j6r537z8y5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: E:\IdeaProjects\AngularProjects\my-blog
distFolder: dist/my-blog
outDir: E:\IdeaProjects\AngularProjects\my-blog\dist\static
handle404: ''
allowErrorCollect: false
